--- # Connection
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo 
  user: ec2-user
  tasks: 
  - name: Install httpd and prerequisites
    when: ( ansible_facts['distribution'] == "Amazon" or ansible_facts['distribution'] == "CentOS" )
    package: 
      name: "{{ item }}" 
      state: present
    with_items:
    - httpd
    - php
    - php
    - wget 