# ansible-playbook IAAC/vpc.yaml 
---
- name: Add ec2
  hosts: localhost
  tasks:
  - name: create a VPC with dedicated tenancy and a couple of tags
    amazon.aws.ec2_vpc_net:
      name: ansible2
      cidr_block: 10.0.0.0/16
      region: us-east-2
      tags:
        module: ec2_vpc_net
        this: works
      tenancy: default
